#!/bin/sh
#
# Description: Shell script to connect automatically to the netsoul server
# You need a modified ns_auth to use this script
#
# Written By: Alpha14 (contact@alpha14.com)
# (3-2015)

version=7
remote_ip="google.fr"
ns_server="ns-server.epitech.net"
ns_auth="ns_auth" # ns_auth location
#internal variables
msg=0
verbose='false'
user=''
tries=0

command -v $ns_auth 2>&1 >/dev/null ||
{ echo "ns_auth not Found. Aborting."; exit 1; }

# Arguments
while getopts 'u:v' flag; do
  case "${flag}" in
    u) user=${OPTARG} ;;
    v) verbose='true' ;;
    *) echo "Unexpected option ${flag}" ;;
  esac
done

xping()
{
    ping -q -c 2 -W 1 "$1" 2>&1 >/dev/null
}

control_c()
{
    message "Exiting (SIGINIT)"
    exit $?
}

# Trap keyboard interrupt
trap control_c SIGINT

network_wait()
{
    gateway=$(ip r | awk '/^def/{print $3}')
    if [ -z "$gateway" ]
    then
	print "No network set" 1
	sleep 1
	network_wait
    else
	ping_ns
    fi
}

ping_ns()
{
    if xping ${gateway}
    then
	wait_ns
    else
	print "Failed to contact gateway"
	sleep 1
	network_wait
    fi
}


wait_ns()
{
    if xping ${ns_server}
    then
	ping_remote
    else
	print "Unable to join netsoul server"
	sleep 1
	ping_ns
    fi
}

ping_remote()
{
    if xping ${remote_ip}
    then
	ping_network
    else
	sleep 1
	ns_connect
    fi
}

ns_connect()
{

    if [ "$tries" -ge 3 ]
    then
        print "Netsoul service seems down"
	sleep 10
    else
	print "Connecting with ns_auth"
    fi

    if [ -n "$user" ]
    then
	$ns_auth -u $user 2>&1 >/dev/null
    else
	$ns_auth 2>&1 >/dev/null
    fi

    sleep 4

    if xping ${remote_ip}
    then
	ping_network
    else
	tries=$(( tries + 1 ))
	ping_ns
    fi
}

ping_network()
{
    if xping ${remote_ip}
    then
	tries=0
	print "Network up"
	sleep 4
	ping_network
    else
        print "Failed to contact network"
	ping_ns
    fi
}

print()
{
    if [ "$msg" != "$1" ]
    then
	logger "Netsoul: $1"
	if [ "$verbose" = true ]
	then
	    echo "[Netsoul] $1"
	fi
	command -v notify-send  2>&1 >/dev/null && notify-send 'Netsoul' "$1" --icon=dialog-information -t 2000  2>&1 >/dev/null
    fi
    msg=$1
}

message()
{
    if [ "$verbose" = true ]
    then
	logger "[Netsoul] $1"
	echo "[Netsoul] $1"
    fi
}

echo "[Netsoul] Script version $version, report suggestions and bugs on https://github.com/alpha14/epitech"

if xping ${remote_ip}
then
    ping_network
else
    network_wait
fi
